export const FETCHING_CATEGORY_PRODUCTS = 'FETCHING_CATEGORY_PRODUCTS',
  FETCHING_CATEGORY_PRODUCTS_SUCCCESS = 'FETCHING_CATEGORY_PRODUCTS_SUCCCESS',
  FETCHING_CATEGORY_PRODUCTS_FAILED = 'FETCHING_CATEGORY_PRODUCTS_FAILED',
  LOW_PRICE_FIRST = 'LOW_PRICE_FIRST',
  HIGH_PRICE_FIRST = 'HIGH_PRICE_FIRST',
  LOAD_MORE = 'LOAD_MORE',
  initialLimit = 10,
  nextLimit = 5;
