export const MOBILE_MODAL_OPEN = 'MOBILE_MODAL_OPEN';
export const MOBILE_MODAL_CLOSE = 'MOBILE_MODAL_CLOSE';
export const DESKTOP_CATEGORY_MODAL_CLOSE = 'DESKTOP_CATEGORY_MODAL_CLOSE';
export const DESKTOP_PAGE_MODAL_CLOSE = 'DESKTOP_PAGE_MODAL_CLOSE';
