export const MOBILE_MODAL_OPEN = 'MOBILE_MODAL_OPEN';
export const MOBILE_MODAL_CLOSE = 'MOBILE_MODAL_CLOSE';
export const DESKTOP_CATEGORY_MODAL = 'DESKTOP_CATEGORY_MODAL';
export const DESKTOP_PAGE_MODAL = 'DESKTOP_PAGE_MODAL';
