export const FETCHING_SEARCH_QUERY = 'FETCHING_SEARCH_QUERY',
  SEARCH_QUERY_FETCHING_SUCCESS = 'SEARCH_QUERY_FETCHING_SUCCESS',
  SEARCH_QUERY_FETCHING_FAILED = 'SEARCH_QUERY_FETCHING_FAILED',
  LOAD_SEARCH_PRODUCTS_MORE = 'LOAD_SEARCH_PRODUCTS_MORE',
  LOW_PRICE_FIRST_SEARCH = 'LOW_PRICE_FIRST_SEARCH',
  HIGH_PRICE_FIRST_SEARCH = 'HIGH_PRICE_FIRST_SEARCH',
  nextLimit = 5,
  initialLimit = 10;
