export const FETCHING_SINGLE_PRODUCT = 'FETCHING_SINGLE_PRODUCT',
  FETCHING_SINGLE_PRODUCT_SUCCESS = 'FETCHING_SINGLE_PRODUCT_SUCCESS',
  FETCHING_SINGLE_PRODUCT_FAILED = 'FETCHING_SINGLE_PRODUCT_FAILED';
